name: Update

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  
  update:
    name: Update
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      -
        name: Fetch sources
        uses: actions/checkout@v4
      -
        name: Set up uv
        uses: astral-sh/setup-uv@v5
      -
        name: Update data
        run: |
          uv run update.py
      -
        name: Commit and push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add .
          git commit -m "Update build numbers"
          git push origin master
